# Get access to the Nengo objects
from ca.nengo.model import *
from ca.nengo.model.impl import *
from ca.nengo.model.nef.impl import *
from ca.nengo.math.impl import *
from ca.nengo.util import *
from numeric import *
from nef import *

#For reading a .txt file generated by matlab to use as input.
#Assumes the network is built.
#Run this from the Nengo input console, with the network open and
#it will add an input node (Input B) that sweep a delta function input across 
#the x domain.  This is used in the paper to generate the tuning
#curves of the spiking neurons.
#To use the input, simply swap the A input and B input connections.

file = open("../models/input_matrix.txt") #to open a file object
A = []
for line in file:
   row = [float(x) for x in line.split()] #we split the line up into its elements and convert them
   A.append(row)

# A = [[float(x) for x in line.split()] for line in file]

mat = array(A) #convert A to an array
in_matrix = []
cols = mat.shape[1]
length = .05 #Length of time to show each input
times = arange(0,length*cols,length)
for row in A:
    #make the row into a piecewise input
    row.append(0)
    in_matrix.append(PiecewiseConstantFunction(times.tolist(), row))

inputB = FunctionInput("Input B", in_matrix, Units.UNK)
net.add(inputB)
    
